
export const CLEARMODAL = "CLEARMODAL";
export const SHOWMODAL = "SHOWMODAL";

///

export const STARTLOADING = "STARTLOADING";
export const FINISHLOADING = "FINISHLOADING";

export const SETACCESS = "SETACCESS";

export const SETALERT = "SETALERT";
export const CLOSEALERT = "CLOSEALERT";

export const CHANGESECTION = "CHANGESECTION";

export const OPENMODAL = "OPENMODAL";
export const CLOSEMODAL = "CLOSEMODAL";

export const SET_IS_ELEMENTS_CHANGED = "SET_IS_ELEMENTS_CHANGED";

export const RESET_IS_SORT_CHANGED = "RESET_IS_SORT_CHANGED";
export const RESET_IS_ELEMENTS_CHANGED = "RESET_IS_ELEMENTS_CHANGED";

export const CHANGE_ELEMENTS_ON_PAGE_COUNT = "CHANGE_ELEMENTS_ON_PAGE_COUNT";
export const CHANGE_ELEMENTS_SORT_DIRECTION = "CHANGE_ELEMENTS_SORT_DIRECTION";
export const CHANGE_ELEMENTS_SORT_BY = "CHANGE_ELEMENTS_SORT_BY";
export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";

export const SET_TOTAL_COUNT = "SET_TOTAL_COUNT";

export const LOGOUT = "LOGOUT";
export const CLEAR_TOTAL_COUNT = "CLEAR_TOTAL_COUNT";

export const UPDATE_COURSES = "UPDATE_COURSES";
export const SET_COURSES = "SET_COURSES";
