export const GETCOURSESSTARTED = "courses/GETCOURSESSTARTED";
export const GETCOURSESFAILED = "courses/GETCOURSESFAILED";
export const GETCOURSESSUCCESS = "courses/GETCOURSESSUCCESS";

export const GETUSERCOURSESSTARTED = "courses/GETUSERCOURSESSTARTED";
export const GETUSERCOURSESSUCCESS = "courses/GETUSERCOURSESSUCCESS";
export const GETUSERCOURSESFAILED = "courses/GETUSERCOURSESFAILED";

export const ENROLLINCOURSESTARTED = "courses/ENROLLINCOURSESTARTED";
export const ENROLLINCOURSESUCCESS = "courses/ENROLLINCOURSESUCCESS";
export const ENROLLINCOURSEFAILED = "courses/ENROLLINCOURSEFAILED";

export const UNSUBSCRIBESTARTED = "courses/UNSUBSCRIBESTARTED";
export const UNSUBSCRIBESUCCESS = "courses/UNSUBSCRIBESUCCESS";
export const UNSUBSCRIBEFAILED = "courses/UNSUBSCRIBEFAILED";

export const REMOVECOURSESTARTED = "courses/REMOVECOURSESTARTED";
export const REMOVECOURSESUCCESS = "courses/REMOVECOURSESUCCESS";
export const REMOVECOURSEFAILED = "courses/REMOVECOURSEFAILED";

export const EDITCOURSESTARTED = "courses/EDITCOURSESTARTED";
export const EDITCOURSESUCCESS = "courses/EDITCOURSESUCCESS";
export const EDITCOURSEFAILED = "courses/EDITCOURSEFAILED";

export const ADDCOURSESTARTED = "courses/ADDCOURSESTARTED";
export const ADDCOURSESUCCESS = "courses/ADDCOURSESUCCESS";
export const ADDCOURSEFAILED = "courses/ADDCOURSEFAILED";

export const CLEARWARNING = "courses/CLEARWARNING";

export const CLEARINFO = "courses/CLEARINFO";