export const GETSTUDENTSSTARTED = "users/GETSTUDENTSSTARTED";
export const GETSTUDENTSFAILED = "users/GETSTUDENTSFAILED";
export const GETSTUDENTSSUCCESS = "users/GETSTUDENTSSUCCESS";

export const REMOVESTUDENTSTARTED = "users/REMOVESTUDENTSSTARTED";
export const REMOVESTUDENTSUCCESS = "users/REMOVESTUDENTSSUCCESS";
export const REMOVESTUDENTFAILED = "users/REMOVESTUDENTSFAILED";

export const EDITSTUDENTSTARTED = "users/EDITSTUDENTSSTARTED";
export const EDITSTUDENTSUCCESS = "users/EDITCSTUDENTSSUCCESS";
export const EDITSTUDENTFAILED = "users/EDITSTUDENTSEFAILED";

export const ADDSTUDENTSTARTED = "users/ADDSTUDENTSSTARTED";
export const ADDSTUDENTSUCCESS = "users/ADDSTUDENTSSUCCESS";
export const ADDSTUDENTFAILED = "users/ADDSTUDENTSFAILED";

export const CLEARWARNING = "users/CLEARWARNING";

export const CLEARINFO = "users/CLEARINFO";