export const GETCOURSESSTARTED = "adminPanel/GETCOURSESSTARTED";
export const GETCOURSESSUCCESS = "adminPanel/GETCOURSESSUCCESS";
export const GETCOURSESFAILED = "adminPanel/GETCOURSESFAILED";

export const EDITCOURSESTARTED = "adminPanel/EDITCOURSESTARTED";
export const EDITCOURSESUCCESS = "adminPanel/EDITCOURSESUCCESS";
export const EDITCOURSEFAILED = "adminPanel/EDITCOURSEFAILED";

export const REMOVECOURSESTARTED = "adminPanel/REMOVECOURSESTARTED";
export const REMOVECOURSESUCCESS = "adminPanel/REMOVECOURSESUCCESS";
export const REMOVECOURSEFAILED = "adminPanel/REMOVECOURSEFAILED";

export const ADDCOURSESTARTED = "adminPanel/ADDCOURSESTARTED";
export const ADDCOURSESUCCESS = "adminPanel/ADDCOURSESUCCESS";
export const ADDCOURSEFAILED = "adminPanel/ADDCOURSEFAILED";

export const GETSTUDENTSSTARTED = "adminPanel/GETSTUDENTSSTARTED";
export const GETSTUDENTSSUCCESS = "adminPanel/GETSTUDENTSSUCCESS";
export const GETSTUDENTSFAILED = "adminPanel/GETSTUDENTSFAILED";