export const CHANGESECTION = "CHANGESECTION";

export const SET_IS_ELEMENTS_CHANGED = "SET_IS_ELEMENTS_CHANGED";

export const RESET_IS_SORT_CHANGED = "RESET_IS_SORT_CHANGED";
export const RESET_IS_ELEMENTS_CHANGED = "RESET_IS_ELEMENTS_CHANGED";

export const CHANGE_ELEMENTS_ON_PAGE_COUNT = "CHANGE_ELEMENTS_ON_PAGE_COUNT";
export const CHANGE_ELEMENTS_SORT_DIRECTION = "CHANGE_ELEMENTS_SORT_DIRECTION";
export const CHANGE_ELEMENTS_SORT_BY = "CHANGE_ELEMENTS_SORT_BY";
export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";

export const SET_TOTAL_COUNT = "SET_TOTAL_COUNT";

export const CLEAR_TOTAL_COUNT = "CLEAR_TOTAL_COUNT";

export const UPDATE_TABLE_DATA = "UPDATE_TABLE_DATA";

export const SET_COURSES = "SET_COURSES";
export const SET_STUDENTS = "SET_STUDENTS";

export const REMOVE_COURSE = "REMOVE_COURSE";
export const REMOVE_STUDENT = "REMOVE_STUDENT";

export const SET_PROFILE_INFO = "SET_PROFILE_INFO";
export const SET_DATE = "SET_DATE";

